id: P85859519
initial_creation_type: ocr
source_metadata:
  volumes:
    3c3e1d20cfb14fa797dafa39ec61cc6b:
      base_file: v079.txt
      image_group_id: I1PD95924
      title: ཆོས་མངོན་པའི་མཛོད་ཀྱི་བཤད་པ།
      total_pages: 1433
      volume_number: 79
